######################################################################
# Automatically generated by qmake (3.0) Fr. Sep. 30 01:03:39 2016
######################################################################

TEMPLATE = subdirs
CONFIG += c++11 ordered

SUBDIRS =	core \
			chotrain \
			chotrainCreator \
			test

TRANSLATIONS += intl/chotrain_de.ts

chotrain.depends = core
chotrainCreator.depends = core
test.depends = core
